#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Community.JobsLauncher.Dashboard.Models;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Community.JobsLauncher.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobLauncherPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobLauncherPage.cshtml"
  
    Layout = new LayoutPage("Job Launcher");


            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n    (function () {\r\n        window.JobLauncher = window.JobLauncher |" +
"| {};\r\n        window.JobLauncher.config = {\r\n            apiBaseUrl: \'");


            
            #line 15 "..\..\Pages\JobLauncherPage.cshtml"
                    Write(Url.To("/joblauncher"));

            
            #line default
            #line hidden
WriteLiteral(@"'
        };
    })();
</script>

<div class=""jobslauncher-dark jobslauncher-page-wrapper"">

    <ul class=""nav nav-tabs"" role=""tablist"">
        <li role=""presentation"" class=""active"">
            <a href=""#launchTab"" aria-controls=""launchTab"" role=""tab"" data-toggle=""tab"">Launch</a>
        </li>
        <li role=""presentation"">
            <a href=""#historyTab"" aria-controls=""historyTab"" role=""tab"" data-toggle=""tab"">History</a>
        </li>
        <li role=""presentation"">
            <a href=""#templatesTab"" aria-controls=""templatesTab"" role=""tab"" data-toggle=""tab"">Templates</a>
        </li>
        <li role=""presentation"" id=""auditLogTab"" class=""jobslauncher-hidden"">
            <a href=""#auditLogPane"" aria-controls=""auditLogPane"" role=""tab"" data-toggle=""tab"">Audit Log</a>
        </li>
    </ul>

    <div class=""tab-content jobslauncher-tab-content"">
        ");


            
            #line 38 "..\..\Pages\JobLauncherPage.cshtml"
   Write(Html.RenderPartial(new _LaunchTab()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 39 "..\..\Pages\JobLauncherPage.cshtml"
   Write(Html.RenderPartial(new _HistoryTab()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 40 "..\..\Pages\JobLauncherPage.cshtml"
   Write(Html.RenderPartial(new _TemplatesTab()));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 41 "..\..\Pages\JobLauncherPage.cshtml"
   Write(Html.RenderPartial(new _AuditLogTab()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    ");


            
            #line 44 "..\..\Pages\JobLauncherPage.cshtml"
Write(Html.RenderPartial(new _CronGeneratorModal()));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 45 "..\..\Pages\JobLauncherPage.cshtml"
Write(Html.RenderPartial(new _CriticalConfirmModal()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
