#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Community.JobsLauncher.Dashboard.Models;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Community.JobsLauncher.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\JobLauncherPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobLauncherPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobLauncherPage.cshtml"
  
    Layout = new LayoutPage("Job Launcher");
    // Asumimos que la clase parcial tiene una propiedad CriticalQueues


            
            #line default
            #line hidden
WriteLiteral("<style>\r\n    #paramsContainer .param-complex {\r\n        border-left: 2px solid #c" +
"cc;\r\n        padding-left: 10px;\r\n        margin-bottom: 10px;\r\n    }\r\n    .para" +
"m-complex label {\r\n        font-weight: normal;\r\n        font-style: italic;\r\n  " +
"  }\r\n    #jsonParams {\r\n        font-family: monospace;\r\n    }\r\n    .help-block " +
".btn {\r\n        margin-right: 5px;\r\n    }\r\n</style>\r\n\r\n<ul class=\"nav nav-tabs\" " +
"role=\"tablist\">\r\n    <li role=\"presentation\" class=\"active\"><a href=\"#launchTab\"" +
" aria-controls=\"launchTab\" role=\"tab\" data-toggle=\"tab\">Launch</a></li>\r\n    <li" +
" role=\"presentation\"><a href=\"#historyTab\" aria-controls=\"historyTab\" role=\"tab\"" +
" data-toggle=\"tab\">History</a></li>\r\n    <li role=\"presentation\"><a href=\"#templ" +
"atesTab\" aria-controls=\"templatesTab\" role=\"tab\" data-toggle=\"tab\">Templates</a>" +
"</li>\r\n</ul>\r\n\r\n<div class=\"tab-content\" style=\"padding-top:15px;\">\r\n    <!-- ==" +
"================== PESTAÑA LAUNCH ==================== -->\r\n    <div role=\"tabpa" +
"nel\" class=\"tab-pane fade in active\" id=\"launchTab\">\r\n        <div class=\"row\">\r" +
"\n            <div class=\"col-md-6\">\r\n                <div class=\"panel panel-def" +
"ault\">\r\n                    <div class=\"panel-heading\">Job Configuration</div>\r\n" +
"                    <div class=\"panel-body\">\r\n                        <div class" +
"=\"form-group\">\r\n                            <label>Mode</label>\r\n               " +
"             <div>\r\n                                <label class=\"radio-inline\">" +
"<input type=\"radio\" name=\"launchMode\" value=\"assisted\" checked> Assisted (assemb" +
"ly)</label>\r\n                                <label class=\"radio-inline\"><input " +
"type=\"radio\" name=\"launchMode\" value=\"manual\"> Manual (JSON)</label>\r\n          " +
"                  </div>\r\n                        </div>\r\n                      " +
"  <!-- Campos según modo -->\r\n                        <div id=\"assistedFields\">\r" +
"\n                            <div class=\"form-group\">\r\n                         " +
"       <label>Class Name</label>\r\n                                <div class=\"in" +
"put-group\">\r\n                                    <input type=\"text\" id=\"classNam" +
"eAssisted\" class=\"form-control\" placeholder=\"Namespace.ClassName\">\r\n            " +
"                        <span class=\"input-group-btn\"><button class=\"btn btn-def" +
"ault\" id=\"btnLoadMethods\" type=\"button\">Load Methods</button></span>\r\n          " +
"                      </div>\r\n                            </div>\r\n              " +
"              <div class=\"form-group\" id=\"methodSelectGroup\" style=\"display:none" +
";\">\r\n                                <label>Method</label>\r\n                    " +
"            <select id=\"methodSelect\" class=\"form-control\"><option value=\"\">-- S" +
"elect method --</option></select>\r\n                            </div>\r\n         " +
"                   <div id=\"paramsContainer\"></div>\r\n                        </d" +
"iv>\r\n                        <div id=\"manualFields\" style=\"display:none;\">\r\n    " +
"                        <div class=\"form-group\">\r\n                              " +
"  <label>Class Name</label>\r\n                                <input type=\"text\" " +
"id=\"classNameManual\" class=\"form-control\" placeholder=\"Namespace.ClassName\">\r\n  " +
"                          </div>\r\n                            <div class=\"form-g" +
"roup\">\r\n                                <label>Method Name</label>\r\n            " +
"                    <input type=\"text\" id=\"methodNameManual\" class=\"form-control" +
"\" placeholder=\"MethodName\">\r\n                            </div>\r\n               " +
"             <div class=\"form-group\">\r\n                                <label>Pa" +
"rameters (JSON)</label>\r\n                                <textarea id=\"jsonParam" +
"s\" class=\"form-control\" rows=\"6\"\r\n                                          plac" +
"eholder=\'{\"to\":\"email@example.com\",\"subject\":\"Test\"}\'></textarea>\r\n             " +
"                   <div class=\"help-block\">\r\n                                   " +
" <button type=\"button\" class=\"btn btn-xs btn-default\" id=\"validateJsonBtn\">Valid" +
"ate</button>\r\n                                    <button type=\"button\" class=\"b" +
"tn btn-xs btn-default\" id=\"formatJsonBtn\">Format</button>\r\n                     " +
"               <button type=\"button\" class=\"btn btn-xs btn-info\" id=\"suggestJson" +
"Btn\">Suggest JSON</button>\r\n                                    <span id=\"jsonVa" +
"lidationMsg\" class=\"text-danger\" style=\"display:none;\">Invalid JSON</span>\r\n    " +
"                            </div>\r\n                            </div>\r\n        " +
"                </div>\r\n                        <!-- Opciones avanzadas -->\r\n   " +
"                     <div class=\"form-group\">\r\n                            <a ro" +
"le=\"button\" data-toggle=\"collapse\" href=\"#advancedOptions\" aria-expanded=\"false\"" +
">Advanced options ▾</a>\r\n                            <div class=\"collapse\" id=\"a" +
"dvancedOptions\" style=\"margin-top:5px;\">\r\n                                <div c" +
"lass=\"checkbox\">\r\n                                    <label><input type=\"checkb" +
"ox\" id=\"chkPerformContext\"> Include PerformContext</label>\r\n                    " +
"            </div>\r\n                                <div class=\"checkbox\">\r\n    " +
"                                <label><input type=\"checkbox\" id=\"chkCancellatio" +
"nToken\"> Include CancellationToken</label>\r\n                                </di" +
"v>\r\n                            </div>\r\n                        </div>\r\n        " +
"                <!-- Modo de ejecución -->\r\n                        <div class=\"" +
"form-group\">\r\n                            <label>Execution Mode</label>\r\n       " +
"                     <div id=\"executionModeGroup\">\r\n                            " +
"    <label class=\"radio-inline\"><input type=\"radio\" name=\"execMode\" value=\"FireA" +
"ndForget\" checked> Fire & Forget</label>\r\n                                <label" +
" class=\"radio-inline\"><input type=\"radio\" name=\"execMode\" value=\"Schedule\"> Sche" +
"dule (minutes)</label>\r\n                                <label class=\"radio-inli" +
"ne\"><input type=\"radio\" name=\"execMode\" value=\"ScheduleDateTime\"> Schedule (date" +
")</label>\r\n                                <label class=\"radio-inline\"><input ty" +
"pe=\"radio\" name=\"execMode\" value=\"Recurring\"> Recurring</label>\r\n               " +
"                 <label class=\"radio-inline\"><input type=\"radio\" name=\"execMode\"" +
" value=\"Continuation\"> Continuation</label>\r\n                            </div>\r" +
"\n                        </div>\r\n                        <!-- Campos específicos" +
" del modo de ejecución -->\r\n                        <div id=\"scheduleFields\" sty" +
"le=\"display:none;\">\r\n                            <div class=\"form-group\">\r\n     " +
"                           <label>Delay (minutes)</label>\r\n                     " +
"           <input type=\"number\" id=\"delayMinutes\" class=\"form-control\" min=\"1\" v" +
"alue=\"30\">\r\n                            </div>\r\n                        </div>\r\n" +
"                        <div id=\"scheduleDateTimeFields\" style=\"display:none;\">\r" +
"\n                            <div class=\"form-group\">\r\n                         " +
"       <label>Scheduled Date (UTC)</label>\r\n                                <inp" +
"ut type=\"datetime-local\" id=\"scheduledDateTime\" class=\"form-control\">\r\n         " +
"                   </div>\r\n                        </div>\r\n                     " +
"   <div id=\"recurringFields\" style=\"display:none;\">\r\n                           " +
" <div class=\"form-group\">\r\n                                <label>Cron Expressio" +
"n</label>\r\n                                <div class=\"input-group\">\r\n          " +
"                          <input type=\"text\" id=\"cronExpression\" class=\"form-con" +
"trol\" placeholder=\"* * * * *\">\r\n                                    <span class=" +
"\"input-group-btn\"><button class=\"btn btn-default\" id=\"btnValidateCron\" type=\"but" +
"ton\">Validate</button></span>\r\n                                </div>\r\n         " +
"                       <div id=\"cronPreview\" style=\"margin-top:5px; display:none" +
";\" class=\"text-info\"></div>\r\n                            </div>\r\n               " +
"             <!-- Motor recurrente (solo visible en modo manual) -->\r\n          " +
"                  <div class=\"form-group\" id=\"recurringEngineGroup\" style=\"displ" +
"ay:none;\">\r\n                                <label>Recurring Engine</label>\r\n   " +
"                             <select id=\"recurringEngine\" class=\"form-control\">\r" +
"\n                                    <option value=\"BuiltIn\">Built-in (lightweig" +
"ht)</option>\r\n                                    <option value=\"DynamicJobs\">Dy" +
"namicJobs (advanced)</option>\r\n                                </select>\r\n      " +
"                          <span id=\"dynamicJobsWarning\" class=\"text-warning\" sty" +
"le=\"display:none;\">DynamicJobs no está instalado en el dashboard o workers.</spa" +
"n>\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div id=\"continuationFields\" style=\"display:none;\">\r\n           " +
"                 <div class=\"form-group\">\r\n                                <labe" +
"l>Parent Job Id</label>\r\n                                <input type=\"text\" id=\"" +
"parentJobId\" class=\"form-control\" placeholder=\"job-id\">\r\n                       " +
"     </div>\r\n                        </div>\r\n                        <!-- Cola -" +
"->\r\n                        <div class=\"form-group\">\r\n                          " +
"  <label>Queue</label>\r\n                            <input type=\"text\" id=\"queue" +
"\" class=\"form-control\" list=\"queueList\" value=\"default\">\r\n                      " +
"      <datalist id=\"queueList\"></datalist>\r\n                            <span id" +
"=\"criticalQueueWarning\" class=\"text-warning\" style=\"display:none;\">⚠ Esta cola r" +
"equiere confirmación.</span>\r\n                        </div>\r\n                  " +
"  </div>\r\n                </div>\r\n            </div>\r\n            <div class=\"co" +
"l-md-6\">\r\n                <div class=\"panel panel-default\">\r\n                   " +
" <div class=\"panel-heading\">Actions</div>\r\n                    <div class=\"panel" +
"-body\">\r\n                        <button type=\"button\" class=\"btn btn-info btn-b" +
"lock\" id=\"btnPreview\">Preview</button>\r\n                        <button type=\"bu" +
"tton\" class=\"btn btn-success btn-block\" id=\"btnLaunch\">Launch Job</button>\r\n    " +
"                    <div id=\"launchResult\" class=\"alert\" style=\"margin-top:10px;" +
" display:none;\"></div>\r\n                    </div>\r\n                </div>\r\n    " +
"            <div class=\"panel panel-default\" id=\"previewPanel\" style=\"display:no" +
"ne;\">\r\n                    <div class=\"panel-heading\">Preview</div>\r\n           " +
"         <div class=\"panel-body\"><pre id=\"previewContent\"></pre></div>\r\n        " +
"        </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <!-- =====" +
"=============== PESTAÑA HISTORY ==================== -->\r\n    <div role=\"tabpane" +
"l\" class=\"tab-pane fade\" id=\"historyTab\">\r\n        <div class=\"panel panel-defau" +
"lt\">\r\n            <div class=\"panel-heading\">\r\n                <div class=\"row\">" +
"\r\n                    <div class=\"col-sm-6\"><strong>Recent launches</strong></di" +
"v>\r\n                    <div class=\"col-sm-6 text-right\"><button class=\"btn btn-" +
"sm btn-danger\" id=\"btnClearHistory\">Clear history</button></div>\r\n              " +
"  </div>\r\n            </div>\r\n            <div class=\"panel-body\">\r\n            " +
"    <table class=\"table table-condensed\" id=\"historyTable\">\r\n                   " +
" <thead><tr><th>Timestamp</th><th>JobId</th><th>Class</th><th>Method</th><th>Que" +
"ue</th><th>Mode</th><th>Engine</th><th></th></tr></thead>\r\n                    <" +
"tbody></tbody>\r\n                </table>\r\n            </div>\r\n        </div>\r\n  " +
"  </div>\r\n\r\n    <!-- ==================== PESTAÑA TEMPLATES ====================" +
" -->\r\n    <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"templatesTab\">\r\n       " +
" <div class=\"row\">\r\n            <div class=\"col-md-8\">\r\n                <div cla" +
"ss=\"panel panel-default\">\r\n                    <div class=\"panel-heading\">Saved " +
"templates</div>\r\n                    <div class=\"panel-body\">\r\n                 " +
"       <table class=\"table table-condensed\" id=\"templatesTable\">\r\n              " +
"              <thead><tr><th>Name</th><th>Class</th><th>Method</th><th>Queue</th" +
"><th>Mode</th><th></th></tr></thead>\r\n                            <tbody></tbody" +
">\r\n                        </table>\r\n                    </div>\r\n               " +
" </div>\r\n            </div>\r\n            <div class=\"col-md-4\">\r\n               " +
" <div class=\"panel panel-default\">\r\n                    <div class=\"panel-headin" +
"g\">Manage</div>\r\n                    <div class=\"panel-body\">\r\n                 " +
"       <button id=\"btnSaveTemplate\" class=\"btn btn-primary btn-block\">Save curre" +
"nt as template</button>\r\n                        <div class=\"form-group\" style=\"" +
"margin-top:10px;\">\r\n                            <label>Import template</label>\r\n" +
"                            <input type=\"file\" id=\"importFile\" accept=\".json\">\r\n" +
"                            <button id=\"btnImport\" class=\"btn btn-default btn-bl" +
"ock\" style=\"margin-top:5px;\">Import</button>\r\n                        </div>\r\n  " +
"                  </div>\r\n                </div>\r\n            </div>\r\n        </" +
"div>\r\n    </div>\r\n</div>\r\n\r\n<!-- Modal de Confirmación para colas críticas -->\r\n" +
"<div class=\"modal fade\" id=\"criticalConfirmModal\" tabindex=\"-1\" role=\"dialog\">\r\n" +
"    <div class=\"modal-dialog\" role=\"document\">\r\n        <div class=\"modal-conten" +
"t\">\r\n            <div class=\"modal-header\"><h4 class=\"modal-title\">Confirm Launc" +
"h</h4></div>\r\n            <div class=\"modal-body\">\r\n                <p>The queue" +
" <strong id=\"criticalQueueName\"></strong> is marked as critical. Are you sure yo" +
"u want to launch this job?</p>\r\n                <div><pre id=\"criticalJobSummary" +
"\"></pre></div>\r\n            </div>\r\n            <div class=\"modal-footer\">\r\n    " +
"            <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">C" +
"ancel</button>\r\n                <button type=\"button\" class=\"btn btn-danger\" id=" +
"\"confirmCriticalLaunch\">Confirm & Launch</button>\r\n            </div>\r\n        <" +
"/div>\r\n    </div>\r\n</div>\r\n\r\n<script>\r\n    // ====== VARIABLES GLOBALES ======\r\n" +
"    var currentMethods = [];        // array de MethodInfoDto\r\n    var dynamicJo" +
"bsAvailable = false;\r\n    var criticalQueues =  [];\r\n    var apiBaseUrl = \'");


            
            #line 245 "..\..\Pages\JobLauncherPage.cshtml"
                 Write(Url.To("/joblauncher"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var selectedMethod = null; // almacenará el MethodInfoDto actual\r\n\r\n    /" +
"/ ====== UTILIDADES ======\r\n    function $$(id){ return document.getElementById(" +
"id); }\r\n    function fetchJson(url, options){ return fetch(url, options).then(r " +
"=> r.json()); }\r\n\r\n    // ====== INICIALIZACIÓN ======\r\n    document.addEventLis" +
"tener(\'DOMContentLoaded\', function() {\r\n        fetchJson(apiBaseUrl + \'/api/cap" +
"abilities\').then(function(caps) {\r\n            dynamicJobsAvailable = caps.dynam" +
"icJobsAvailable;\r\n            adjustRecurringEngineDisplay();\r\n        });\r\n    " +
"    loadQueues();\r\n        bindEvents();\r\n        loadHistory();\r\n        loadTe" +
"mplates();\r\n    });\r\n\r\n    function bindEvents() {\r\n        // Modo\r\n        var" +
" radios = document.querySelectorAll(\'input[name=\"launchMode\"]\');\r\n        radios" +
".forEach(function(r) { r.addEventListener(\'change\', toggleMode); });\r\n\r\n        " +
"// Load methods\r\n        $$(\'btnLoadMethods\').addEventListener(\'click\', loadMeth" +
"ods);\r\n\r\n        // Method select\r\n        $$(\'methodSelect\').addEventListener(\'" +
"change\', onMethodChange);\r\n\r\n        // Execution modes\r\n        var execRadios " +
"= document.querySelectorAll(\'input[name=\"execMode\"]\');\r\n        execRadios.forEa" +
"ch(function(r) { r.addEventListener(\'change\', toggleExecMode); });\r\n\r\n        //" +
" Validate/format JSON/ suggest\r\n        $$(\'validateJsonBtn\').addEventListener(\'" +
"click\', validateJson);\r\n        $$(\'formatJsonBtn\').addEventListener(\'click\', fo" +
"rmatJson);\r\n        $$(\'suggestJsonBtn\').addEventListener(\'click\', suggestJsonSt" +
"ructure);\r\n\r\n        // Cron\r\n        $$(\'btnValidateCron\').addEventListener(\'cl" +
"ick\', validateCron);\r\n\r\n        // Botones principales\r\n        $$(\'btnPreview\')" +
".addEventListener(\'click\', showPreview);\r\n        $$(\'btnLaunch\').addEventListen" +
"er(\'click\', submitJob);\r\n        $$(\'confirmCriticalLaunch\').addEventListener(\'c" +
"lick\', confirmedLaunch);\r\n\r\n        // History\r\n        $$(\'btnClearHistory\').ad" +
"dEventListener(\'click\', clearHistory);\r\n\r\n        // Templates\r\n        $$(\'btnS" +
"aveTemplate\').addEventListener(\'click\', saveTemplate);\r\n        $$(\'btnImport\')." +
"addEventListener(\'click\', importTemplate);\r\n\r\n        // Atajo Ctrl+Enter\r\n     " +
"   document.addEventListener(\'keydown\', function(e) {\r\n            if (e.ctrlKey" +
" && e.key === \'Enter\') { e.preventDefault(); submitJob(); }\r\n        });\r\n\r\n    " +
"    // Mostrar/esconder campos de ejecución\r\n        toggleExecMode();\r\n        " +
"toggleMode();\r\n\r\n    }\r\n\r\n    // ====== MODO ASISTIDO / MANUAL ======\r\n    funct" +
"ion toggleMode() {\r\n        var mode = document.querySelector(\'input[name=\"launc" +
"hMode\"]:checked\').value;\r\n        if (mode === \'assisted\') {\r\n            $$(\'as" +
"sistedFields\').style.display = \'block\';\r\n            $$(\'manualFields\').style.di" +
"splay = \'none\';\r\n        } else {\r\n            $$(\'assistedFields\').style.displa" +
"y = \'none\';\r\n            $$(\'manualFields\').style.display = \'block\';\r\n        }\r" +
"\n        toggleExecMode(); // para mostrar/ocultar motor recurrente según modo\r\n" +
"    }\r\n\r\n    // ====== MODO DE EJECUCIÓN ======\r\n    function toggleExecMode() {" +
"\r\n        var mode = document.querySelector(\'input[name=\"execMode\"]:checked\').va" +
"lue;\r\n        $$(\'scheduleFields\').style.display = (mode === \'Schedule\') ? \'bloc" +
"k\' : \'none\';\r\n        $$(\'scheduleDateTimeFields\').style.display = (mode === \'Sc" +
"heduleDateTime\') ? \'block\' : \'none\';\r\n        $$(\'recurringFields\').style.displa" +
"y = (mode === \'Recurring\') ? \'block\' : \'none\';\r\n        $$(\'continuationFields\')" +
".style.display = (mode === \'Continuation\') ? \'block\' : \'none\';\r\n\r\n        // Mot" +
"or recurrente visible solo si estamos en Recurring y en modo manual\r\n        adj" +
"ustRecurringEngineDisplay();\r\n    }\r\n\r\n    function adjustRecurringEngineDisplay" +
"() {\r\n        var mode = document.querySelector(\'input[name=\"launchMode\"]:checke" +
"d\').value;\r\n        var execMode = document.querySelector(\'input[name=\"execMode\"" +
"]:checked\').value;\r\n        if (execMode === \'Recurring\' && mode === \'manual\') {" +
"\r\n            $$(\'recurringEngineGroup\').style.display = \'block\';\r\n            v" +
"ar optDynamic = $$(\'recurringEngine\').querySelector(\'option[value=\"DynamicJobs\"]" +
"\');\r\n            if (!dynamicJobsAvailable) {\r\n                optDynamic.disabl" +
"ed = true;\r\n                $$(\'dynamicJobsWarning\').style.display = \'inline\';\r\n" +
"            } else {\r\n                optDynamic.disabled = false;\r\n            " +
"    $$(\'dynamicJobsWarning\').style.display = \'none\';\r\n            }\r\n        } e" +
"lse {\r\n            $$(\'recurringEngineGroup\').style.display = \'none\';\r\n        }" +
"\r\n    }\r\n\r\n    // Ajusta cuando se cambie de ejecución o modo\r\n    document.quer" +
"ySelectorAll(\'input[name=\"execMode\"]\').forEach(r => r.addEventListener(\'change\'," +
" adjustRecurringEngineDisplay));\r\n    document.querySelectorAll(\'input[name=\"lau" +
"nchMode\"]\').forEach(r => r.addEventListener(\'change\', adjustRecurringEngineDispl" +
"ay));\r\n\r\n    // ====== CARGAR MÉTODOS (ASISTIDO) ======\r\n    function loadMethod" +
"s() {\r\n        var className = $$(\'classNameAssisted\').value.trim();\r\n        if" +
" (!className) { alert(\'Class name required\'); return; }\r\n        fetchJson(apiBa" +
"seUrl + \'/api/methods?className=\' + encodeURIComponent(className))\r\n            " +
".then(function(resp) {\r\n                if (!resp.success) {\r\n                  " +
"  alert(resp.error + \' Switched to manual mode.\');\r\n                    document" +
".querySelector(\'input[name=\"launchMode\"][value=\"manual\"]\').checked = true;\r\n    " +
"                toggleMode();\r\n                    return;\r\n                }\r\n " +
"               currentMethods = resp.methods;\r\n                var sel = $$(\'met" +
"hodSelect\');\r\n                sel.innerHTML = \'<option value=\"\">-- Select method" +
" --</option>\';\r\n                currentMethods.forEach(function(m, i) {\r\n       " +
"             var params = m.parameters.map(function(p) { return p.name; }).join(" +
"\', \');\r\n                    var display = m.methodName + \'(\' + params + \')\';\r\n  " +
"                  sel.innerHTML += \'<option value=\"\' + i + \'\">\' + display + \'</o" +
"ption>\';\r\n                });\r\n                $$(\'methodSelectGroup\').style.dis" +
"play = \'block\';\r\n                $$(\'paramsContainer\').innerHTML = \'\';\r\n        " +
"    });\r\n    }\r\n\r\n    // ====== GENERAR PARÁMETROS DINÁMICOS (ASISTIDO) ======\r\n" +
"    function onMethodChange() {\r\n        var idx = $$(\'methodSelect\').value;\r\n  " +
"      if (idx === \'\') { \r\n            $$(\'paramsContainer\').innerHTML = \'\'; \r\n  " +
"          selectedMethod = null; \r\n            return; \r\n        }\r\n        var " +
"method = currentMethods[parseInt(idx)];\r\n        selectedMethod = method;\r\n     " +
"   var html = \'\';\r\n    \r\n        method.parameters.forEach(function(p) {\r\n      " +
"      html += \'<div class=\"form-group param-field\">\';\r\n            html += \'<lab" +
"el>\' + p.name + \' (\' + p.type + \')</label>\';\r\n        \r\n            if (p.isComp" +
"lex) {\r\n                // Editor JSON para tipos complejos\r\n                htm" +
"l += \'<textarea class=\"form-control param-complex\" data-param-name=\"\' + p.name +" +
" \'\" rows=\"3\" placeholder=\\\'Insert JSON for \' + p.type + \'\\\'></textarea>\';\r\n     " +
"       } else {\r\n                html += generateInputForSimpleType(p);\r\n       " +
"     }\r\n            html += \'</div>\';\r\n        });\r\n        $$(\'paramsContainer\'" +
").innerHTML = html;\r\n    }\r\n\r\n    function generateInputForSimpleType(paramInfo)" +
" {\r\n        var type = paramInfo.type;\r\n        var name = paramInfo.name;\r\n    " +
"    var isNullable = type.endsWith(\'?\');\r\n        var underlyingType = isNullabl" +
"e ? type.slice(0, -1).toLowerCase() : type.toLowerCase();\r\n    \r\n        var htm" +
"l = \'\';\r\n    \r\n        // Números enteros\r\n        if (underlyingType.includes(\'" +
"int\') || underlyingType.includes(\'long\') || \r\n            underlyingType.include" +
"s(\'short\') || underlyingType.includes(\'byte\')) {\r\n            html = \'<input typ" +
"e=\"number\" class=\"form-control\" data-param-name=\"\' + name + \'\" step=\"1\" value=\"\'" +
" + (isNullable ? \'\' : \'0\') + \'\" />\';\r\n        }\r\n        // Números flotantes\r\n " +
"       else if (underlyingType.includes(\'double\') || underlyingType.includes(\'fl" +
"oat\') || \r\n                 underlyingType.includes(\'decimal\') || underlyingType" +
".includes(\'single\')) {\r\n            html = \'<input type=\"number\" class=\"form-con" +
"trol\" data-param-name=\"\' + name + \'\" step=\"any\" value=\"\' + (isNullable ? \'\' : \'0" +
".0\') + \'\" />\';\r\n        }\r\n        // Booleanos (select True/False + opción vací" +
"a si anulable)\r\n        else if (underlyingType.includes(\'bool\')) {\r\n           " +
" html = \'<select class=\"form-control\" data-param-name=\"\' + name + \'\">\';\r\n       " +
"     if (isNullable) html += \'<option value=\"\">-- Not set --</option>\';\r\n       " +
"     html += \'<option value=\"true\">True</option><option value=\"false\">False</opt" +
"ion>\';\r\n            html += \'</select>\';\r\n        }\r\n        // Fechas y horas\r\n" +
"        else if (underlyingType.includes(\'datetime\') || underlyingType.includes(" +
"\'datetimeoffset\')) {\r\n            var defaultDate = isNullable ? \'\' : new Date(n" +
"ew Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().slic" +
"e(0, 16);\r\n            html = \'<input type=\"datetime-local\" class=\"form-control\"" +
" data-param-name=\"\' + name + \'\" value=\"\' + defaultDate + \'\" />\';\r\n            ht" +
"ml += \'<small class=\"help-block\">Click the calendar icon to select a date and ti" +
"me.</small>\';\r\n        }\r\n        // Fecha sin hora (date)\r\n        else if (und" +
"erlyingType === \'system.datetime\' || underlyingType === \'datetime\') {\r\n         " +
"   var defaultDate = isNullable ? \'\' : new Date().toISOString().slice(0, 10);\r\n " +
"           html = \'<input type=\"date\" class=\"form-control\" data-param-name=\"\' + " +
"name + \'\" value=\"\' + defaultDate + \'\" />\';\r\n        }\r\n        // GUID\r\n        " +
"else if (underlyingType === \'system.guid\' || underlyingType === \'guid\') {\r\n     " +
"       html = \'<input type=\"text\" class=\"form-control\" data-param-name=\"\' + name" +
" + \'\" placeholder=\"00000000-0000-0000-0000-000000000000\" value=\"\' + (isNullable " +
"? \'\' : \'00000000-0000-0000-0000-000000000000\') + \'\" />\';\r\n        }\r\n        // " +
"TimeSpan\r\n        else if (underlyingType === \'system.timespan\' || underlyingTyp" +
"e === \'timespan\') {\r\n            html = \'<input type=\"text\" class=\"form-control\"" +
" data-param-name=\"\' + name + \'\" placeholder=\"hh:mm:ss\" value=\"\' + (isNullable ? " +
"\'\' : \'00:00:00\') + \'\" />\';\r\n        }\r\n        // Enum (tratado como texto)\r\n   " +
"     else if (underlyingType.includes(\'.\') && !underlyingType.startsWith(\'system" +
".\')) {\r\n            html = \'<input type=\"text\" class=\"form-control\" data-param-n" +
"ame=\"\' + name + \'\" placeholder=\"Enum value of \' + paramInfo.type + \'\" />\';\r\n    " +
"    }\r\n        // Cadena y otros\r\n        else {\r\n            html = \'<input typ" +
"e=\"text\" class=\"form-control\" data-param-name=\"\' + name + \'\" placeholder=\"\' + pa" +
"ramInfo.type + \'\" />\';\r\n        }\r\n    \r\n        if (isNullable) {\r\n            " +
"html += \'<small class=\"text-muted\">(Optional, leave empty for null)</small>\';\r\n " +
"       }\r\n    \r\n        return html;\r\n    }\r\n\r\n    // ====== JSON VALIDATE / FOR" +
"MAT / SUGGEST ======\r\n    function validateJson() {\r\n        var text = $$(\'json" +
"Params\').value.trim();\r\n        if (!text) return;\r\n        try { JSON.parse(tex" +
"t); $$(\'jsonValidationMsg\').style.display = \'none\'; alert(\'Valid JSON.\'); }\r\n   " +
"     catch(e) { $$(\'jsonValidationMsg\').style.display = \'inline\'; }\r\n    }\r\n    " +
"function formatJson() {\r\n        var text = $$(\'jsonParams\').value.trim();\r\n    " +
"    try { var obj = JSON.parse(text); $$(\'jsonParams\').value = JSON.stringify(ob" +
"j, null, 2); $$(\'jsonValidationMsg\').style.display = \'none\'; }\r\n        catch(e)" +
" { $$(\'jsonValidationMsg\').style.display = \'inline\'; }\r\n    }\r\n\r\n    function su" +
"ggestJsonStructure() {\r\n        var className = $$(\'classNameManual\').value.trim" +
"();\r\n        var methodName = $$(\'methodNameManual\').value.trim();\r\n    \r\n      " +
"  if (!className || !methodName) {\r\n            alert(\'Please enter Class Name a" +
"nd Method Name first.\');\r\n            return;\r\n        }\r\n    \r\n        // Llama" +
"r a la API para obtener los métodos\r\n        fetchJson(apiBaseUrl + \'/api/method" +
"s?className=\' + encodeURIComponent(className))\r\n            .then(function(resp)" +
" {\r\n                if (!resp.success) {\r\n                    alert(\'Assembly no" +
" disponible: \' + resp.error);\r\n                    return;\r\n                }\r\n " +
"               // Buscar el método especificado\r\n                var method = re" +
"sp.methods.find(function(m) { return m.methodName === methodName; });\r\n         " +
"       if (!method) {\r\n                    alert(\'Method not found.\');\r\n        " +
"            return;\r\n                }\r\n            \r\n                // Generar" +
" un objeto JSON con valores por defecto según los tipos\r\n                var sug" +
"gestion = {};\r\n                method.parameters.forEach(function(p) {\r\n        " +
"            suggestion[p.name] = getDefaultValueForType(p.type, p.isComplex);\r\n " +
"               });\r\n            \r\n                // Formatear el JSON y mostrar" +
"lo en el textarea\r\n                $$(\'jsonParams\').value = JSON.stringify(sugge" +
"stion, null, 2);\r\n            })\r\n            .catch(function(err) {\r\n          " +
"      alert(\'Error loading suggestion: \' + err.message);\r\n            });\r\n    }" +
"\r\n\r\n    function getDefaultValueForType(type, isComplex) {\r\n        if (type.end" +
"sWith(\'?\')) {\r\n            return null; // anulable, sugerimos null\r\n        }\r\n" +
"        if (isComplex) {\r\n            return {}; // objeto vacío como placeholde" +
"r\r\n        }\r\n        var t = type.toLowerCase();\r\n        if (t.includes(\'int\')" +
" || t.includes(\'long\') || t.includes(\'short\') || t.includes(\'byte\')) return 0;\r\n" +
"        if (t.includes(\'double\') || t.includes(\'float\') || t.includes(\'decimal\')" +
" || t.includes(\'single\')) return 0.0;\r\n        if (t.includes(\'bool\')) return tr" +
"ue;\r\n        if (t.includes(\'datetime\') || t.includes(\'datetimeoffset\')) return " +
"new Date().toISOString();\r\n        if (t === \'system.guid\' || t === \'guid\') retu" +
"rn \'00000000-0000-0000-0000-000000000000\';\r\n        if (t === \'system.timespan\' " +
"|| t === \'timespan\') return \'00:00:00\';\r\n        if (t === \'system.string\' || t " +
"=== \'string\') return \'\';\r\n        // Para enums, intentamos extraer el primer va" +
"lor posible (no disponible aquí, dejamos string vacío)\r\n        return \'\';\r\n}\r\n\r" +
"\n    // ====== VALIDATE CRON ======\r\n    function validateCron() {\r\n        var " +
"expr = $$(\'cronExpression\').value.trim();\r\n        if (!expr) { alert(\'Cron expr" +
"ession required\'); return; }\r\n        fetchJson(apiBaseUrl + \'/pi/validate-cron?" +
"expression=\' + encodeURIComponent(expr))\r\n            .then(function(resp) {\r\n  " +
"              var div = $$(\'cronPreview\');\r\n                if (!resp.success) {" +
"\r\n                    div.innerHTML = \'<span class=\"text-danger\">\' + resp.error " +
"+ \'</span>\';\r\n                } else {\r\n                    div.innerHTML = \'Nex" +
"t occurrences: \' + resp.occurrences.join(\', \');\r\n                }\r\n            " +
"    div.style.display = \'block\';\r\n            });\r\n    }\r\n\r\n    // ====== COLAS " +
"CRÍTICAS ======\r\n    function isQueueCritical(queue) {\r\n        return criticalQ" +
"ueues.indexOf(queue) >= 0;\r\n    }\r\n\r\n    function checkCriticalQueue(queue) {\r\n " +
"       if (isQueueCritical(queue)) {\r\n            $$(\'criticalQueueWarning\').sty" +
"le.display = \'block\';\r\n            return true;\r\n        } else {\r\n            $" +
"$(\'criticalQueueWarning\').style.display = \'none\';\r\n            return false;\r\n  " +
"      }\r\n    }\r\n\r\n    // Verificar al escribir\r\n    $$(\'queue\').addEventListener" +
"(\'input\', function() { checkCriticalQueue(this.value); });\r\n    $$(\'queue\').addE" +
"ventListener(\'change\', function() { checkCriticalQueue(this.value); });\r\n\r\n    /" +
"/ ====== CARGAR COLAS ======\r\n    function loadQueues() {\r\n        fetchJson(api" +
"BaseUrl + \'/api/queues\').then(function(resp) {\r\n            var datalist = $$(\'q" +
"ueueList\');\r\n            datalist.innerHTML = \'\';\r\n            (resp.queues || [" +
"]).forEach(function(q) {\r\n                datalist.innerHTML += \'<option value=\"" +
"\' + q + \'\">\';\r\n            });\r\n        });\r\n    }\r\n\r\n    // ====== BUILD REQUES" +
"T OBJECT ======\r\n    function convertToType(value, type, isComplex) {\r\n        /" +
"/ Detectar si el tipo es anulable (termina en \'?\')\r\n        var isNullable = typ" +
"e.endsWith(\'?\');\r\n        var underlyingType = isNullable ? type.slice(0, -1).to" +
"LowerCase() : type.toLowerCase();\r\n    \r\n        // Si el campo está vacío o es " +
"null y es anulable, retornar null\r\n        if (isNullable && (value === \'\' || va" +
"lue === null || value === undefined)) {\r\n            return null;\r\n        }\r\n  " +
"  \r\n        // Para tipos complejos, ya se parsea el JSON\r\n        if (isComplex" +
") {\r\n            if (value === \'\' && isNullable) return null;\r\n            try {" +
"\r\n                return JSON.parse(value);\r\n            } catch(e) {\r\n         " +
"       return value; // fallback\r\n            }\r\n        }\r\n    \r\n        // A c" +
"ontinuación, la conversión normal pero usando underlyingType\r\n        if (underl" +
"yingType.includes(\'int\') || underlyingType.includes(\'long\') || \r\n            und" +
"erlyingType.includes(\'short\') || underlyingType.includes(\'byte\')) {\r\n           " +
" var num = parseInt(value, 10);\r\n            return isNaN(num) ? (isNullable ? n" +
"ull : value) : num;\r\n        }\r\n        if (underlyingType.includes(\'double\') ||" +
" underlyingType.includes(\'float\') || \r\n            underlyingType.includes(\'deci" +
"mal\') || underlyingType.includes(\'single\')) {\r\n            var num = parseFloat(" +
"value);\r\n            return isNaN(num) ? (isNullable ? null : value) : num;\r\n   " +
"     }\r\n        if (underlyingType.includes(\'bool\')) {\r\n            if (typeof v" +
"alue === \'boolean\') return value;\r\n            if (value === \'\' && isNullable) r" +
"eturn null;\r\n            return value === \'true\' || value === \'1\' || value === \'" +
"on\';\r\n        }\r\n        // Fechas se envían como string ISO, se mantienen igual" +
"\r\n        // Para otros, string\r\n        return value;\r\n    }\r\n\r\n\r\n    function " +
"buildRequest() {\r\n        var mode = document.querySelector(\'input[name=\"launchM" +
"ode\"]:checked\').value;\r\n        var className = mode === \'assisted\' ? $$(\'classN" +
"ameAssisted\').value.trim() : $$(\'classNameManual\').value.trim();\r\n        var me" +
"thodName = mode === \'assisted\' ? (function() {\r\n            var idx = $$(\'method" +
"Select\').value;\r\n            return idx === \'\' ? \'\' : currentMethods[parseInt(id" +
"x)].methodName;\r\n        })() : $$(\'methodNameManual\').value.trim();\r\n\r\n        " +
"var request = {\r\n            className: className,\r\n            methodName: meth" +
"odName,\r\n            queue: $$(\'queue\').value.trim() || \'default\',\r\n            " +
"executionMode: document.querySelector(\'input[name=\"execMode\"]:checked\').value,\r\n" +
"            includePerformContext: $$(\'chkPerformContext\').checked,\r\n           " +
" includeCancellationToken: $$(\'chkCancellationToken\').checked,\r\n            para" +
"meters: null,\r\n            rawParametersJson: null\r\n        };\r\n\r\n        // Si " +
"manual, rawParametersJson\r\n        if (mode === \'manual\') {\r\n            request" +
".rawParametersJson = $$(\'jsonParams\').value.trim() || \'{}\';\r\n        } else {\r\n " +
"           // Modo asistido: construir objeto con valores tipados\r\n            v" +
"ar paramsObj = {};\r\n            var paramFields = document.querySelectorAll(\'#pa" +
"ramsContainer .param-field\');\r\n            paramFields.forEach(function(field) {" +
"\r\n                var input = field.querySelector(\'[data-param-name]\');\r\n       " +
"         var name = input.getAttribute(\'data-param-name\');\r\n                var " +
"rawValue;\r\n                if (input.type === \'checkbox\') {\r\n                   " +
" rawValue = input.checked;\r\n                } else {\r\n                    rawVal" +
"ue = input.value;\r\n                }\r\n                // Buscar la definición de" +
"l parámetro en el método seleccionado\r\n                var paramDef = selectedMe" +
"thod ? selectedMethod.parameters.find(function(p) { return p.name === name; }) :" +
" null;\r\n                if (paramDef) {\r\n                    var convertedValue " +
"= convertToType(rawValue, paramDef.type, paramDef.isComplex);\r\n                 " +
"   paramsObj[name] = convertedValue;\r\n                } else {\r\n                " +
"    paramsObj[name] = rawValue; // fallback\r\n                }\r\n            });\r" +
"\n            request.rawParametersJson = JSON.stringify(paramsObj);\r\n           " +
" request.parameters = null; // no usar el diccionario de strings\r\n        }\r\n\r\n " +
"       // Completion specific\r\n        if (request.executionMode === \'Schedule\')" +
" {\r\n            request.delayMinutes = parseInt($$(\'delayMinutes\').value) || 30;" +
"\r\n        }\r\n        if (request.executionMode === \'ScheduleDateTime\') {\r\n      " +
"      request.scheduledDateTime = $$(\'scheduledDateTime\').value ? new Date($$(\'s" +
"cheduledDateTime\').value).toISOString() : null;\r\n        }\r\n        if (request." +
"executionMode === \'Recurring\') {\r\n            request.cronExpression = $$(\'cronE" +
"xpression\').value.trim() || \'* * * * *\';\r\n            if (mode === \'manual\') {\r\n" +
"                request.recurringEngine = $$(\'recurringEngine\').value;\r\n        " +
"    }\r\n        }\r\n        if (request.executionMode === \'Continuation\') {\r\n     " +
"       request.parentJobId = $$(\'parentJobId\').value.trim();\r\n        }\r\n       " +
" return request;\r\n    }\r\n\r\n    // ====== PREVIEW ======\r\n    function showPrevie" +
"w() {\r\n        var req = buildRequest();\r\n        var summary = \'Class: \' + req." +
"className + \'\\nMethod: \' + req.methodName + \'\\nQueue: \' + req.queue +\r\n         " +
"             \'\\nMode: \' + req.executionMode + \'\\nEngine: \' + (req.recurringEngin" +
"e || \'Direct\') +\r\n                      \'\\nParameters: \' + (req.rawParametersJso" +
"n || JSON.stringify(req.parameters));\r\n        $$(\'previewContent\').textContent " +
"= summary;\r\n        $$(\'previewPanel\').style.display = \'block\';\r\n    }\r\n\r\n    //" +
" ====== SUBMIT / LAUNCH ======\r\n    var pendingLaunchRequest = null; // para con" +
"firmación de cola crítica\r\n\r\n    function submitJob() {\r\n        var req = build" +
"Request();\r\n        if (!req.className || !req.methodName) { alert(\'ClassName an" +
"d MethodName are required.\'); return; }\r\n\r\n        if (isQueueCritical(req.queue" +
")) {\r\n            pendingLaunchRequest = req;\r\n            $$(\'criticalQueueName" +
"\').textContent = req.queue;\r\n            $$(\'criticalJobSummary\').textContent = " +
"\'Class: \' + req.className + \'\\nMethod: \' + req.methodName + \'\\nMode: \' + req.exe" +
"cutionMode;\r\n            $(\'#criticalConfirmModal\').modal(\'show\');\r\n        } el" +
"se {\r\n            launchJob(req);\r\n        }\r\n    }\r\n\r\n    function confirmedLau" +
"nch() {\r\n        $(\'#criticalConfirmModal\').modal(\'hide\');\r\n        if (pendingL" +
"aunchRequest) launchJob(pendingLaunchRequest);\r\n    }\r\n\r\n    function launchJob(" +
"req) {\r\n        var formData = new FormData();\r\n        formData.append(\'json\', " +
"JSON.stringify(req));\r\n\r\n        fetch(apiBaseUrl + \'/api/launch\', {\r\n          " +
"  method: \'POST\',\r\n            body: formData\r\n        })\r\n        .then(functio" +
"n(r) { return r.json(); })\r\n          .then(function(result) {\r\n              va" +
"r alertDiv = $$(\'launchResult\');\r\n              alertDiv.style.display = \'block\'" +
";\r\n              if (result.success) {\r\n                  alertDiv.className = \'" +
"alert alert-success\';\r\n                  alertDiv.innerHTML = \'Job launched succ" +
"essfully! <a href=\"\' + result.link + \'\" target=\"_blank\">\' + result.jobId + \'</a>" +
"\';\r\n                  loadQueues(); // actualizar colas\r\n                  loadH" +
"istory(); // recargar historial\r\n              } else {\r\n                  alert" +
"Div.className = \'alert alert-danger\';\r\n                  alertDiv.textContent = " +
"\'Error: \' + (result.error || \'Unknown error\');\r\n              }\r\n          }).ca" +
"tch(function(err) {\r\n              var alertDiv = $$(\'launchResult\');\r\n         " +
"     alertDiv.style.display = \'block\';\r\n              alertDiv.className = \'aler" +
"t alert-danger\';\r\n              alertDiv.textContent = \'Network error: \' + err.m" +
"essage;\r\n          });\r\n    }\r\n\r\n    // ====== HISTORY ======\r\n    function load" +
"History() {\r\n        fetchJson(apiBaseUrl + \'/api/history\').then(function(entrie" +
"s) {\r\n            var tbody = $$(\'historyTable\').querySelector(\'tbody\');\r\n      " +
"      tbody.innerHTML = \'\';\r\n            entries.forEach(function(e) {\r\n        " +
"        var row = \'<tr>\' +\r\n                    \'<td>\' + new Date(e.timestamp).t" +
"oLocaleString() + \'</td>\' +\r\n                    \'<td><a href=\"/jobs/details/\' +" +
" e.jobId + \'\" target=\"_blank\">\' + e.jobId + \'</a></td>\' +\r\n                    \'" +
"<td>\' + e.className + \'</td>\' +\r\n                    \'<td>\' + e.methodName + \'</" +
"td>\' +\r\n                    \'<td>\' + e.queue + \'</td>\' +\r\n                    \'<" +
"td>\' + e.mode + \'</td>\' +\r\n                    \'<td>\' + e.engine + \'</td>\' +\r\n  " +
"                  \'<td>\' +\r\n                    \'<button class=\"btn btn-xs btn-d" +
"efault relaunch\" data-entry=\\\'\' + JSON.stringify(e).replace(/\'/g, \"&#39;\") + \'\\\'" +
">Relaunch</button> \' +\r\n                    \'<button class=\"btn btn-xs btn-defau" +
"lt clone-launch\" data-entry=\\\'\' + JSON.stringify(e).replace(/\'/g, \"&#39;\") + \'\\\'" +
">Clone & Launch</button>\' +\r\n                    \'</td>\' +\r\n                    " +
"\'</tr>\';\r\n                tbody.innerHTML += row;\r\n            });\r\n            " +
"// Bind events\r\n            document.querySelectorAll(\'.relaunch\').forEach(funct" +
"ion(btn) {\r\n                btn.addEventListener(\'click\', function() {\r\n        " +
"            var entry = JSON.parse(this.getAttribute(\'data-entry\'));\r\n          " +
"          loadEntryToForm(entry);\r\n                    document.querySelector(\'." +
"nav-tabs a[href=\"#launchTab\"]\').click();\r\n                });\r\n            });\r\n" +
"            document.querySelectorAll(\'.clone-launch\').forEach(function(btn) {\r\n" +
"                btn.addEventListener(\'click\', function() {\r\n                    " +
"var entry = JSON.parse(this.getAttribute(\'data-entry\'));\r\n                    if" +
" (confirm(\'Clone and launch job with same parameters?\')) {\r\n                    " +
"    var req = buildRequestFromHistory(entry);\r\n                        launchJob" +
"(req);\r\n                    }\r\n                });\r\n            });\r\n        });" +
"\r\n    }\r\n\r\n    function clearHistory() {\r\n        if (!confirm(\'Clear history?\')" +
") return;\r\n        fetch(apiBaseUrl + \'/api/history\', { method: \'DELETE\' }).then" +
"(function() { loadHistory(); });\r\n    }\r\n\r\n    function loadEntryToForm(entry) {" +
"\r\n        // Cargar datos en el formulario (modo manual o asistido)\r\n        if " +
"(entry.mode === \'Manual\') {\r\n            document.querySelector(\'input[name=\"lau" +
"nchMode\"][value=\"manual\"]\').checked = true;\r\n            toggleMode();\r\n        " +
"    $$(\'classNameManual\').value = entry.className;\r\n            $$(\'methodNameMa" +
"nual\').value = entry.methodName;\r\n            $$(\'jsonParams\').value = entry.par" +
"ametersJson;\r\n        } else {\r\n            document.querySelector(\'input[name=\"" +
"launchMode\"][value=\"assisted\"]\').checked = true;\r\n            toggleMode();\r\n   " +
"         $$(\'classNameAssisted\').value = entry.className;\r\n            // Intent" +
"ar cargar métodos para restaurar el select (complejo, omitido por brevedad)\r\n   " +
"         $$(\'paramsContainer\').innerHTML = \'<div class=\"text-info\">Parameters re" +
"stored: \' + entry.parametersJson + \'</div>\';\r\n        }\r\n        // Otros campos" +
"\r\n        if (entry.executionMode) {\r\n            var radio = document.querySele" +
"ctor(\'input[name=\"execMode\"][value=\"\' + entry.executionMode + \'\"]\');\r\n          " +
"  if (radio) radio.checked = true;\r\n            toggleExecMode();\r\n        }\r\n  " +
"      $$(\'queue\').value = entry.queue;\r\n        $$(\'chkPerformContext\').checked " +
"= entry.includePerformContext;\r\n        $$(\'chkCancellationToken\').checked = ent" +
"ry.includeCancellationToken;\r\n    }\r\n\r\n    function buildRequestFromHistory(entr" +
"y) {\r\n        return {\r\n            className: entry.className,\r\n            met" +
"hodName: entry.methodName,\r\n            queue: entry.queue,\r\n            executi" +
"onMode: entry.executionMode,\r\n            cronExpression: entry.cronExpression,\r" +
"\n            delayMinutes: entry.delayMinutes,\r\n            scheduledDateTime: e" +
"ntry.scheduledDateTime,\r\n            parentJobId: entry.parentJobId,\r\n          " +
"  recurringEngine: entry.engine === \'DynamicJobs\' ? \'DynamicJobs\' : \'BuiltIn\',\r\n" +
"            includePerformContext: entry.includePerformContext,\r\n            inc" +
"ludeCancellationToken: entry.includeCancellationToken,\r\n            rawParameter" +
"sJson: entry.parametersJson,\r\n            parameters: null\r\n        };\r\n    }\r\n\r" +
"\n    // ====== TEMPLATES ======\r\n    function loadTemplates() {\r\n        fetchJs" +
"on(apiBaseUrl + \'/api/templates\').then(function(templates) {\r\n            var tb" +
"ody = $$(\'templatesTable\').querySelector(\'tbody\');\r\n            tbody.innerHTML " +
"= \'\';\r\n            templates.forEach(function(t) {\r\n                var row = \'<" +
"tr>\' +\r\n                    \'<td>\' + t.name + \'</td>\' +\r\n                    \'<t" +
"d>\' + t.className + \'</td>\' +\r\n                    \'<td>\' + t.methodName + \'</td" +
">\' +\r\n                    \'<td>\' + t.queue + \'</td>\' +\r\n                    \'<td" +
">\' + t.executionMode + \'</td>\' +\r\n                    \'<td>\' +\r\n                " +
"    \'<button class=\"btn btn-xs btn-default load-template\" data-name=\"\' + t.name " +
"+ \'\">Load</button> \' +\r\n                    \'<button class=\"btn btn-xs btn-defau" +
"lt clone-template\" data-name=\"\' + t.name + \'\">Clone & Launch</button> \' +\r\n     " +
"               \'<button class=\"btn btn-xs btn-danger delete-template\" data-name=" +
"\"\' + t.name + \'\">Delete</button> \' +\r\n                    \'<button class=\"btn bt" +
"n-xs btn-info export-template\" data-name=\"\' + t.name + \'\">Export</button>\' +\r\n  " +
"                  \'</td>\' +\r\n                    \'</tr>\';\r\n                tbody" +
".innerHTML += row;\r\n            });\r\n            bindTemplateEvents();\r\n        " +
"});\r\n    }\r\n\r\n    function bindTemplateEvents() {\r\n        document.querySelecto" +
"rAll(\'.load-template\').forEach(function(btn) {\r\n            btn.addEventListener" +
"(\'click\', function() {\r\n                var name = this.getAttribute(\'data-name\'" +
");\r\n                fetchJson(apiBaseUrl + \'/api/templates?name=\' + encodeURICom" +
"ponent(name))\r\n                    .then(function(t) { loadTemplateToForm(t); do" +
"cument.querySelector(\'.nav-tabs a[href=\"#launchTab\"]\').click(); });\r\n           " +
" });\r\n        });\r\n        document.querySelectorAll(\'.clone-template\').forEach(" +
"function(btn) {\r\n            btn.addEventListener(\'click\', function() {\r\n       " +
"         var name = this.getAttribute(\'data-name\');\r\n                fetchJson(a" +
"piBaseUrl + \'/api/templates?name=\' + encodeURIComponent(name))\r\n                " +
"    .then(function(t) {\r\n                        var req = buildRequestFromTempl" +
"ate(t);\r\n                        if (confirm(\'Clone and launch?\')) launchJob(req" +
");\r\n                    });\r\n            });\r\n        });\r\n        document.quer" +
"ySelectorAll(\'.delete-template\').forEach(function(btn) {\r\n            btn.addEve" +
"ntListener(\'click\', function() {\r\n                var name = this.getAttribute(\'" +
"data-name\');\r\n                if (confirm(\'Delete template \' + name + \'?\')) {\r\n " +
"                   fetch(apiBaseUrl + \'/api/templates?name=\' + encodeURIComponen" +
"t(name), { method: \'DELETE\' })\r\n                        .then(function() { loadT" +
"emplates(); });\r\n                }\r\n            });\r\n        });\r\n        docume" +
"nt.querySelectorAll(\'.export-template\').forEach(function(btn) {\r\n            btn" +
".addEventListener(\'click\', function() {\r\n                var name = this.getAttr" +
"ibute(\'data-name\');\r\n                window.open(\'/joblauncher/api/export-import" +
"?action=export&templateName=\' + encodeURIComponent(name), \'_blank\');\r\n          " +
"  });\r\n        });\r\n    }\r\n\r\n    function saveTemplate() {\r\n        var req = bu" +
"ildRequest();\r\n        if (!req.className || !req.methodName) { alert(\'Class and" +
" method required.\'); return; }\r\n        var name = prompt(\'Template name:\');\r\n  " +
"      if (!name) return;\r\n        var template = {\r\n            name: name,\r\n   " +
"         className: req.className,\r\n            methodName: req.methodName,\r\n   " +
"         queue: req.queue,\r\n            executionMode: req.executionMode,\r\n     " +
"       cronExpression: req.cronExpression,\r\n            delayMinutes: req.delayM" +
"inutes,\r\n            scheduledDateTime: req.scheduledDateTime,\r\n            pare" +
"ntJobId: req.parentJobId,\r\n            recurringEngine: req.recurringEngine,\r\n  " +
"          includePerformContext: req.includePerformContext,\r\n            include" +
"CancellationToken: req.includeCancellationToken,\r\n            parameters: req.pa" +
"rameters,\r\n            rawParametersJson: req.rawParametersJson\r\n        };\r\n   " +
"     var formData = new FormData();\r\n        formData.append(\'json\', JSON.string" +
"ify(template));\r\n        fetch(apiBaseUrl + \'/api/templates\', { method: \'POST\', " +
"body: formData })\r\n            .then(function(r) { return r.json(); })\r\n        " +
"    .then(function(res) { alert(res.message || \'Saved.\'); loadTemplates(); });\r\n" +
"    }\r\n\r\n    function loadTemplateToForm(template) {\r\n        if (template.rawPa" +
"rametersJson) {\r\n            document.querySelector(\'input[name=\"launchMode\"][va" +
"lue=\"manual\"]\').checked = true;\r\n            toggleMode();\r\n            $$(\'clas" +
"sNameManual\').value = template.className;\r\n            $$(\'methodNameManual\').va" +
"lue = template.methodName;\r\n            $$(\'jsonParams\').value = template.rawPar" +
"ametersJson;\r\n        } else {\r\n            document.querySelector(\'input[name=\"" +
"launchMode\"][value=\"assisted\"]\').checked = true;\r\n            toggleMode();\r\n   " +
"         $$(\'classNameAssisted\').value = template.className;\r\n            // car" +
"gar métodos similar a loadEntryToForm (incompleto)\r\n        }\r\n        // Resto " +
"de campos\r\n        var radio = document.querySelector(\'input[name=\"execMode\"][va" +
"lue=\"\' + template.executionMode + \'\"]\');\r\n        if (radio) radio.checked = tru" +
"e;\r\n        toggleExecMode();\r\n        $$(\'queue\').value = template.queue;\r\n    " +
"    $$(\'chkPerformContext\').checked = template.includePerformContext;\r\n        $" +
"$(\'chkCancellationToken\').checked = template.includeCancellationToken;\r\n    }\r\n\r" +
"\n    function buildRequestFromTemplate(template) {\r\n        return {\r\n          " +
"  className: template.className,\r\n            methodName: template.methodName,\r\n" +
"            queue: template.queue,\r\n            executionMode: template.executio" +
"nMode,\r\n            cronExpression: template.cronExpression,\r\n            delayM" +
"inutes: template.delayMinutes,\r\n            scheduledDateTime: template.schedule" +
"dDateTime,\r\n            parentJobId: template.parentJobId,\r\n            recurrin" +
"gEngine: template.recurringEngine,\r\n            includePerformContext: template." +
"includePerformContext,\r\n            includeCancellationToken: template.includeCa" +
"ncellationToken,\r\n            rawParametersJson: template.rawParametersJson,\r\n  " +
"          parameters: template.parameters\r\n        };\r\n    }\r\n\r\n    function imp" +
"ortTemplate() {\r\n    var fileInput = $$(\'importFile\');\r\n    if (!fileInput.files" +
"[0]) { alert(\'Select a file.\'); return; }\r\n    var reader = new FileReader();\r\n " +
"   reader.onload = function(e) {\r\n        var template = JSON.parse(e.target.res" +
"ult);\r\n        var formData = new FormData();\r\n        formData.append(\'json\', J" +
"SON.stringify(template));\r\n        fetch(apiBaseUrl + \'/api/templates\', { method" +
": \'POST\', body: formData })\r\n            .then(function(r) { return r.json(); })" +
"\r\n            .then(function(res) {\r\n                if (res.conflict) {\r\n      " +
"              if (confirm(res.message + \' Overwrite?\')) {\r\n                     " +
"   fetch(apiBaseUrl + \'/api/templates\', { method: \'POST\', body: formData })\r\n   " +
"                         .then(function() { loadTemplates(); });\r\n              " +
"      }\r\n                } else {\r\n                    alert(res.message || \'Imp" +
"orted.\');\r\n                    loadTemplates();\r\n                }\r\n            " +
"});\r\n    };\r\n    reader.readAsText(fileInput.files[0]);\r\n}\r\n</script>");


        }
    }
}
#pragma warning restore 1591
