#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_CriticalConfirmModal.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\_CriticalConfirmModal.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _CriticalConfirmModal : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral(@"<div class=""modal fade"" id=""criticalConfirmModal"" tabindex=""-1"" role=""dialog"">
    <div class=""modal-dialog"" role=""document"">
        <div class=""modal-content"">
            <div class=""modal-header""><h4 class=""modal-title"">Confirm Launch</h4></div>
            <div class=""modal-body"">
                <p>The queue <strong id=""criticalQueueName""></strong> is marked as critical. Are you sure you want to launch this job?</p>
                <div><pre id=""criticalJobSummary""></pre></div>
            </div>
            <div class=""modal-footer"">
                <button type=""button"" class=""btn btn-default"" data-dismiss=""modal"">Cancel</button>
                <button type=""button"" class=""btn btn-danger"" id=""confirmCriticalLaunch"">Confirm & Launch</button>
            </div>
        </div>
    </div>
</div>");


        }
    }
}
#pragma warning restore 1591
