#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_HistoryTab.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\_HistoryTab.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _HistoryTab : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"historyTab\">\r\n    <div class=\"pane" +
"l panel-default\">\r\n        <div class=\"panel-heading\">\r\n            <div class=\"" +
"row\">\r\n                <div class=\"col-sm-6\"><strong>Recent launches</strong></d" +
"iv>\r\n                <div class=\"col-sm-6 text-right\"><button class=\"btn btn-sm " +
"btn-danger\" id=\"btnClearHistory\">Clear history</button></div>\r\n            </div" +
">\r\n        </div>\r\n        <div class=\"panel-body\">\r\n            <table class=\"t" +
"able table-condensed\" id=\"historyTable\">\r\n                <thead><tr><th>Timesta" +
"mp</th><th>JobId</th><th>Class</th><th>Method</th><th>Queue</th><th>Mode</th><th" +
">Engine</th><th></th></tr></thead>\r\n                <tbody></tbody>\r\n           " +
" </table>\r\n            <div class=\"row jobslauncher-history-pagination\">\r\n      " +
"          <div class=\"col-sm-6\">\r\n                    <span id=\"historyPageInfo\"" +
"></span>\r\n                </div>\r\n                <div class=\"col-sm-6 text-righ" +
"t\">\r\n                    <button class=\"btn btn-xs btn-default\" id=\"btnPrevPage\"" +
" disabled>Prev</button>\r\n                    <button class=\"btn btn-xs btn-defau" +
"lt\" id=\"btnNextPage\" disabled>Next</button>\r\n                </div>\r\n           " +
" </div>\r\n            <div class=\"alert alert-info jobslauncher-history-alert\">\r\n" +
"                <strong>About the buttons:</strong>\r\n                <ul class=\"" +
"jobslauncher-no-margin-bottom\">\r\n                    <li><strong>Relaunch:</stro" +
"ng> Loads this job\'s parameters into the Launch tab so you can review or modify " +
"them before launching.</li>\r\n                    <li><strong>Clone & Launch:</st" +
"rong> Immediately creates and enqueues an identical job without editing.</li>\r\n " +
"               </ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
