#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_LaunchTab.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\_LaunchTab.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _LaunchTab : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<div role=\"tabpanel\" class=\"tab-pane fade in active jobslauncher-dark\" id=\"launch" +
"Tab\">\r\n    <div class=\"row\">\r\n        <div class=\"col-md-6\">\r\n            <div c" +
"lass=\"panel panel-default\">\r\n                <div class=\"panel-heading\">Job Conf" +
"iguration</div>\r\n                <div class=\"panel-body\">\r\n\r\n                   " +
" <div class=\"form-group\">\r\n                        <label>Mode</label>\r\n        " +
"                <div>\r\n                            <label class=\"radio-inline\">\r" +
"\n                                <input type=\"radio\" name=\"launchMode\" value=\"as" +
"sisted\" checked> Assisted (assembly)\r\n                            </label>\r\n    " +
"                        <label class=\"radio-inline\">\r\n                          " +
"      <input type=\"radio\" name=\"launchMode\" value=\"manual\"> Manual (JSON)\r\n     " +
"                       </label>\r\n                        </div>\r\n               " +
"     </div>\r\n\r\n                    <div id=\"assistedFields\">\r\n                  " +
"      <div class=\"form-group\">\r\n                            <label>Class Name</l" +
"abel>\r\n                            <div class=\"input-group\">\r\n                  " +
"              <input type=\"text\" id=\"classNameAssisted\" class=\"form-control\" pla" +
"ceholder=\"Namespace.ClassName\">\r\n                                <span class=\"in" +
"put-group-btn\">\r\n                                    <button class=\"btn btn-defa" +
"ult\" id=\"btnLoadMethods\" type=\"button\">Load Methods</button>\r\n                  " +
"              </span>\r\n                            </div>\r\n                     " +
"   </div>\r\n                        <div class=\"form-group jobslauncher-hidden\" i" +
"d=\"methodSelectGroup\">\r\n                            <label>Method</label>\r\n     " +
"                       <select id=\"methodSelect\" class=\"form-control\">\r\n        " +
"                        <option value=\"\">-- Select method --</option>\r\n         " +
"                   </select>\r\n                        </div>\r\n                  " +
"      <div id=\"paramsContainer\"></div>\r\n                    </div>\r\n\r\n          " +
"          <div id=\"manualFields\" class=\"jobslauncher-hidden\">\r\n                 " +
"       <div class=\"form-group\">\r\n                            <label>Class Name</" +
"label>\r\n                            <input type=\"text\" id=\"classNameManual\" clas" +
"s=\"form-control\" placeholder=\"Namespace.ClassName\">\r\n                        </d" +
"iv>\r\n                        <div class=\"form-group\">\r\n                         " +
"   <label>Method Name</label>\r\n                            <input type=\"text\" id" +
"=\"methodNameManual\" class=\"form-control\" placeholder=\"MethodName\">\r\n            " +
"            </div>\r\n                        <div class=\"form-group\">\r\n          " +
"                  <label>Parameters (JSON)</label>\r\n                            " +
"<textarea id=\"jsonParams\" class=\"form-control\" rows=\"6\"\r\n                       " +
"               placeholder=\'{\"to\":\"email@example.com\",\"subject\":\"Test\"}\'></texta" +
"rea>\r\n                            <div class=\"help-block\">\r\n                    " +
"            <button type=\"button\" class=\"btn btn-xs btn-default\" id=\"validateJso" +
"nBtn\">Validate</button>\r\n                                <button type=\"button\" c" +
"lass=\"btn btn-xs btn-default\" id=\"formatJsonBtn\">Format</button>\r\n              " +
"                  <button type=\"button\" class=\"btn btn-xs btn-info\" id=\"suggestJ" +
"sonBtn\">Suggest JSON</button>\r\n                                <span id=\"jsonVal" +
"idationMsg\" class=\"text-danger jobslauncher-hidden\">Invalid JSON</span>\r\n       " +
"                     </div>\r\n                        </div>\r\n                   " +
" </div>\r\n\r\n                    <div class=\"form-group\">\r\n                       " +
" <label>Execution Mode</label>\r\n                        <div id=\"executionModeGr" +
"oup\">\r\n                            <label class=\"radio-inline\"><input type=\"radi" +
"o\" name=\"execMode\" value=\"FireAndForget\" checked> Fire &amp; Forget</label>\r\n   " +
"                         <label class=\"radio-inline\"><input type=\"radio\" name=\"e" +
"xecMode\" value=\"Schedule\"> Schedule (minutes)</label>\r\n                         " +
"   <label class=\"radio-inline\"><input type=\"radio\" name=\"execMode\" value=\"Schedu" +
"leDateTime\"> Schedule (date)</label>\r\n                            <label class=\"" +
"radio-inline\"><input type=\"radio\" name=\"execMode\" value=\"Recurring\"> Recurring</" +
"label>\r\n                            <label class=\"radio-inline\"><input type=\"rad" +
"io\" name=\"execMode\" value=\"Continuation\"> Continuation</label>\r\n                " +
"        </div>\r\n                    </div>\r\n\r\n                    <div id=\"sched" +
"uleFields\" class=\"jobslauncher-hidden\">\r\n                        <div class=\"for" +
"m-group\">\r\n                            <label>Delay (minutes)</label>\r\n         " +
"                   <input type=\"number\" id=\"delayMinutes\" class=\"form-control\" m" +
"in=\"1\" value=\"30\">\r\n                        </div>\r\n                    </div>\r\n" +
"\r\n                    <div id=\"scheduleDateTimeFields\" class=\"jobslauncher-hidde" +
"n\">\r\n                        <div class=\"form-group\">\r\n                         " +
"   <label>Scheduled Date (UTC)</label>\r\n                            <input type=" +
"\"datetime-local\" id=\"scheduledDateTime\" class=\"form-control\">\r\n                 " +
"       </div>\r\n                    </div>\r\n\r\n                    <div id=\"recurr" +
"ingFields\" class=\"jobslauncher-hidden\">\r\n                        <div class=\"for" +
"m-group\">\r\n                            <label>Cron Expression</label>\r\n         " +
"                   <div class=\"input-group\">\r\n                                <i" +
"nput type=\"text\" id=\"cronExpression\" class=\"form-control\" placeholder=\"* * * * *" +
"\">\r\n                                <span class=\"input-group-btn\">\r\n            " +
"                        <button class=\"btn btn-default\" id=\"btnValidateCron\" typ" +
"e=\"button\">Validate</button>\r\n                                    <button type=\"" +
"button\" class=\"btn btn-default\" id=\"btnOpenCronGenerator\">Generate</button>\r\n   " +
"                             </span>\r\n                            </div>\r\n      " +
"                      <div id=\"cronPreview\" class=\"jobslauncher-cron-preview tex" +
"t-info\"></div>\r\n                        </div>\r\n                        <div cla" +
"ss=\"form-group\" id=\"recurringEngineGroup\">\r\n                            <label>R" +
"ecurring Engine</label>\r\n                            <select id=\"recurringEngine" +
"\" class=\"form-control\"></select>\r\n                            <span id=\"dynamicJ" +
"obsWarning\" class=\"text-warning jobslauncher-hidden\">\r\n                         " +
"       DynamicJobs no esta instalado en el dashboard o workers.\r\n               " +
"             </span>\r\n                        </div>\r\n                    </div>" +
"\r\n\r\n                    <div id=\"continuationFields\" class=\"jobslauncher-hidden\"" +
">\r\n                        <div class=\"form-group\">\r\n                           " +
" <label>Parent Job Id</label>\r\n                            <input type=\"text\" id" +
"=\"parentJobId\" class=\"form-control\" placeholder=\"job-id\">\r\n                     " +
"   </div>\r\n                    </div>\r\n\r\n                    <div class=\"form-gr" +
"oup\">\r\n                        <label>Queue</label>\r\n                        <in" +
"put type=\"text\" id=\"queue\" class=\"form-control\" list=\"queueList\" value=\"default\"" +
">\r\n                        <datalist id=\"queueList\"></datalist>\r\n               " +
"         <span id=\"criticalQueueWarning\" class=\"text-warning jobslauncher-hidden" +
"\">\r\n                            Esta cola requiere confirmacion.\r\n              " +
"          </span>\r\n                    </div>\r\n\r\n                </div>\r\n       " +
"     </div>\r\n        </div>\r\n        <div class=\"col-md-6\">\r\n            <div cl" +
"ass=\"panel panel-default\">\r\n                <div class=\"panel-heading\">Actions</" +
"div>\r\n                <div class=\"panel-body\">\r\n                    <button type" +
"=\"button\" class=\"btn btn-info btn-block\" id=\"btnPreview\">Preview</button>\r\n     " +
"               <button type=\"button\" class=\"btn btn-success btn-block\" id=\"btnLa" +
"unch\">Launch Job</button>\r\n                    <button type=\"button\" class=\"btn " +
"btn-warning btn-block jobslauncher-mt-5\" id=\"btnSaveAsTemplate\">Save as Template" +
"</button>\r\n                    <div id=\"launchResult\" class=\"alert jobslauncher-" +
"launch-result\"></div>\r\n                </div>\r\n            </div>\r\n            <" +
"div class=\"panel panel-default jobslauncher-hidden\" id=\"previewPanel\">\r\n        " +
"        <div class=\"panel-heading\">Preview</div>\r\n                <div class=\"pa" +
"nel-body\">\r\n                    <pre id=\"previewContent\"></pre>\r\n               " +
" </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
