#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.JobLauncher.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\_TemplatesTab.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\_TemplatesTab.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class _TemplatesTab : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<div role=\"tabpanel\" class=\"tab-pane fade\" id=\"templatesTab\">\r\n    <div class=\"ro" +
"w\">\r\n        <div class=\"col-md-8\">\r\n            <div class=\"panel panel-default" +
"\">\r\n                <div class=\"panel-heading\">Saved templates</div>\r\n          " +
"      <div class=\"panel-body\">\r\n                    <table class=\"table table-co" +
"ndensed\" id=\"templatesTable\">\r\n                        <thead><tr><th>Name</th><" +
"th>Class</th><th>Method</th><th>Queue</th><th>Mode</th><th></th></tr></thead>\r\n " +
"                       <tbody></tbody>\r\n                    </table>\r\n          " +
"      </div>\r\n            </div>\r\n        </div>\r\n        <div class=\"col-md-4\">" +
"\r\n            <div class=\"panel panel-default\">\r\n                <div class=\"pan" +
"el-heading\">Manage</div>\r\n                <div class=\"panel-body\">\r\n            " +
"        <p><small>You can also create a template from any job in the <strong>His" +
"tory</strong> tab using the <em>Save as template</em> button.</small></p>\r\n     " +
"               <div class=\"form-group jobslauncher-mt-10\">\r\n                    " +
"    <label>Import template</label>\r\n                        <input type=\"file\" i" +
"d=\"importFile\" accept=\".json\">\r\n                        <button id=\"btnImport\" c" +
"lass=\"btn btn-default btn-block jobslauncher-mt-5\">Import</button>\r\n            " +
"        </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    " +
"</div>\r\n    <!-- Modal para vista previa de plantilla -->\r\n    <div class=\"modal" +
" fade\" id=\"templatePreviewModal\" tabindex=\"-1\" role=\"dialog\">\r\n        <div clas" +
"s=\"modal-dialog modal-lg\" role=\"document\">\r\n            <div class=\"modal-conten" +
"t\">\r\n                <div class=\"modal-header\">\r\n                    <button typ" +
"e=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n                " +
"    <h4 class=\"modal-title\">Template Preview: <span id=\"previewTemplateName\"></s" +
"pan></h4>\r\n                </div>\r\n                <div class=\"modal-body\">\r\n   " +
"                 <dl class=\"dl-horizontal\">\r\n                        <dt>Class</" +
"dt><dd id=\"prevClass\"></dd>\r\n                        <dt>Method</dt><dd id=\"prev" +
"Method\"></dd>\r\n                        <dt>Queue</dt><dd id=\"prevQueue\"></dd>\r\n " +
"                       <dt>Execution Mode</dt><dd id=\"prevExecMode\"></dd>\r\n     " +
"                   <dt>Cron Expression</dt><dd id=\"prevCron\"></dd>\r\n            " +
"            <dt>Recurring Engine</dt><dd id=\"prevEngine\"></dd>\r\n                " +
"        <dt>Mode</dt><dd id=\"prevMode\"></dd>\r\n                        <dt>Perfor" +
"m Context</dt><dd id=\"prevPerformContext\"></dd>\r\n                        <dt>Can" +
"cellation Token</dt><dd id=\"prevCancellationToken\"></dd>\r\n                      " +
"  <dt>Params (raw JSON)</dt>\r\n                        <dd><pre id=\"prevParams\" c" +
"lass=\"jobslauncher-params-preview\"></pre></dd>\r\n                    </dl>\r\n     " +
"           </div>\r\n                <div class=\"modal-footer\">\r\n                 " +
"   <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</but" +
"ton>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</" +
"div>");


        }
    }
}
#pragma warning restore 1591
